config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/:id' => 'users#show', as: :user
  
  resources :polishes do
  	resources :reviews, except: [:index], controller: 'polishes/reviews'
  	resources :favorites, only: [:create, :destroy]
  	resources :wants, only: [:create, :destroy]
  	resources :owns, only: [:create, :destroy]
  end
  root 'welcome#index'
end

app/models/polish.rb
class Polish < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	belongs_to :user
	has_many :reviews, dependent: :destroy
  	has_many :favorites, dependent: :destroy
  	has_many :favorite_users, through: :favorites, source: :user
  	has_many :owns, dependent: :destroy
  	has_many :owned_users, through: :owns, source: :user
  	has_many :wants, dependent: :destroy
  	has_many :wanted_users, through: :wants, source: :user

	default_scope {order('created_at DESC')}

	validates :brand, length: { minimum: 3 }, presence: true
	validates :name, length: { minimum: 5 }, presence: true
	validates :color, presence: true
	validates :style, presence: true
	validates :user, presence: true
end

app/controllers/polishes/reviews_controller.rb
class Polishes::ReviewsController < ApplicationController
	def show
		@polish = Polish.find(params[:polish_id])
		authorize @polish
		@review = Review.find(params[:id])
	end

	def new
		@polish = Polish.find(params[:polish_id])
		@review = Review.new
		authorize @review
	end

	def create
		@polish = Polish.find(params[:polish_id])
		@review = current_user.reviews.build(review_params)
		@review.polish = @polish

		authorize @review
		if @review.save
			redirect_to [@polish, @review], notice: "Review was saved."
		else
			flash[:error] = "There was an error saving your review, please try again."
			render :new
		end
	end

	def destroy
		@polish = Polish.find(params[:polish_id])
		@review = Review.find(params[:id])

		title = @review.title
		authorize @review

		if @review.destroy
			flash[:notice] = "\"#{title}\" was deleted successfully."
			redirect_to @polish
		else
			flash[:error] = "There was a problem deleting the review. Please try again."
			render :show
		end
	end

	def edit
		@polish = Polish.find(params[:polish_id])
		@review = Review.find(params[:id])
		authorize @review
	end

	def update
		@polish = Polish.find(params[:polish_id])
		@review = Review.find(params[:id])

		authorize @review
		
		if @review.update_attributes(review_params)
			flash[:notice] = "Review was updated."
			redirect_to [@polish, @review]
		else
			flash[:error] = "There was a problem saving this review, please try again."
			render :new
		end
	end

	private

	def review_params
		params.require(:review).permit(:title, :body)
	end
end

app/controllers/polishes_controller.rb
class PolishesController < ApplicationController
  def index
  	@polishes = Polish.all
    authorize @polishes
  end

  def show
  	@polish = Polish.find(params[:id])
    @reviews = @polish.reviews
    @review = Review.new
    @favorited = @polish.favorite_users
    @wanted = @polish.wanted_users
    @owned = @polish.owned_users
  end

  def new
    @polish = Polish.new
    authorize @polish
  end

  def create
    @polish = current_user.polishes.build(polish_params)
    authorize @polish
    if @polish.save
      flash[:notice] = "Polish saved!"
      redirect_to @polish
    else
      flash[:error] = "There was a problem saving your polish. Please try again."
      render :new
    end
  end

  def destroy
    @polish = Polish.find(params[:id])
    name = @polish.name

    authorize @polish
    if @polish.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to polishes_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end

  def edit
    @polish = Polish.find(params[:id])
    authorize @polish
  end

  def update
    @polish = Polish.find(params[:id])
    authorize @polish
    if @polish.update_attributes(polish_params)
      flash[:notice] = "Polish details updated."
      redirect_to @polish
    else
      flash[:error] = "There was an error saving this polish. Please try again!"
      render :edit
    end
  end

  private
  def polish_params
    params.require(:polish).permit(:brand, :name, :color, :style)
  end
end

app/helpers/polishes_helper.rb
module PolishesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/polishes/reviews/_form.html.erb
<%= form_for [polish, review] do |f| %>
  <% if review.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(review.errors.count, "error") %>.</h4>
      <ul>
        <% review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(review.errors[:title]) do %>
	<%= f.label :title %>
	<%= f.text_field :title, :size => "60" %>
  <% end %>
  <%= form_group_tag(review.errors[:body]) do %>
	<%= f.label :body %>
	<%= f.text_area :body, :cols => "75", :rows => "15" %>
  <% end %>
  <div class="form-group">
	<%= f.submit "Save" %>
  </div>
<% end %>

app/views/polishes/reviews/_review.html.erb
<%= content_tag :div, class: 'media', id: "review-#{review.id}" do %>
	<div class="media-body">
		<p><%= review.title %> <em> Written by <%= review.user.name %></em></p>
		<p><%= review.body %></p>
	</div>
	<% end %>

app/views/polishes/reviews/edit.html.erb
<div class="container">
	<h1>Edit Review</h1>
	<div class="row">
		<div class="col-md-4">
			Edit an existing review.
		</div>
		<div class="col-md-8">
		<%= render partial: 'form', locals: { polish: @polish, review: @review } %>
		</div>
	</div>
</div>

app/views/polishes/reviews/index.html.erb
<div class="container">
	<h1>Reviews</h1>
	<% if policy(Review.new).create? %>
	<%= link_to "New Review", new_review_path, class: 'btn btn-success' %>
	<% end %>

	<% @reviews.each do |review| %>
	<div class="media">
		<div class="media-body">
			<h4 class="media-heading">
				<%= link_to review.title, review %>
			</h4>
			<small>
				By <%= review.user.name %>
			</small>
		</div>
	</div>
	<% end %>
</div>

app/views/polishes/reviews/new.html.erb
<div class="container">
	<h1>Add Review</h1>
	<div class="row">
		<div class="col-md-4">
			Write a new review.
		</div>
		<div class="col-md-8">
			<%= render partial: 'form', locals: { polish: @polish, review: @review } %>
		</div>
	</div>
</div>

app/views/polishes/reviews/show.html.erb
<div class="container">
	<h1><%= @review.title %> <small>by <%= @review.user.name %></small></h1>
	<div class="col-md-10">
		<%= @review.body %>
		<br/>
		<small>Written about <%= link_to "#{@polish.brand}'s #{@polish.name}", polish_path(@polish) %></small>
	<% if policy(@review).update? %>
	<br/>
			<%= link_to ("<i class='fa fa-pencil'></i> Edit").html_safe, edit_polish_review_path(@polish, @review), class: 'btn btn-default' %>
	       <%= link_to ("<i class='fa fa-trash-o'></i> Delete").html_safe, [@polish, @review], method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure you want to delete this review?' } %>
	<% end %>
	</div>
</div>