config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/:id' => 'users#show', as: :user
  
  resources :polishes do
  	resources :reviews, except: [:index], controller: 'polishes/reviews'
  	resources :favorites, only: [:create, :destroy]
  	resources :wants, only: [:create, :destroy]
  	resources :owns, only: [:create, :destroy]
  end
  root 'welcome#index'
end

app/models/polish.rb
class Polish < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	belongs_to :user
	has_many :reviews, dependent: :destroy
  	has_many :favorites, dependent: :destroy
  	has_many :favorite_users, through: :favorites, source: :user
  	has_many :owns, dependent: :destroy
  	has_many :owned_users, through: :owns, source: :user
  	has_many :wants, dependent: :destroy
  	has_many :wanted_users, through: :wants, source: :user

	default_scope {order('created_at DESC')}

	validates :brand, length: { minimum: 3 }, presence: true
	validates :name, length: { minimum: 5 }, presence: true
	validates :color, presence: true
	validates :style, presence: true
	validates :user, presence: true
end

app/controllers/polishes/reviews_controller.rb
class Polishes::ReviewsController < ApplicationController
	def show
		@polish = Polish.find(params[:polish_id])
		authorize @polish
		@review = Review.find(params[:id])
	end

	def new
		@polish = Polish.find(params[:polish_id])
		@review = Review.new
		authorize @review
	end

	def create
		@polish = Polish.find(params[:polish_id])
		@review = current_user.reviews.build(review_params)
		@review.polish = @polish

		authorize @review
		if @review.save
			redirect_to [@polish, @review], notice: "Review was saved."
		else
			flash[:error] = "There was an error saving your review, please try again."
			render :new
		end
	end

	def destroy
		@polish = Polish.find(params[:polish_id])
		@review = Review.find(params[:id])

		title = @review.title
		authorize @review

		if @review.destroy
			flash[:notice] = "\"#{title}\" was deleted successfully."
			redirect_to @polish
		else
			flash[:error] = "There was a problem deleting the review. Please try again."
			render :show
		end
	end

	def edit
		@polish = Polish.find(params[:polish_id])
		@review = Review.find(params[:id])
		authorize @review
	end

	def update
		@polish = Polish.find(params[:polish_id])
		@review = Review.find(params[:id])

		authorize @review
		
		if @review.update_attributes(review_params)
			flash[:notice] = "Review was updated."
			redirect_to [@polish, @review]
		else
			flash[:error] = "There was a problem saving this review, please try again."
			render :new
		end
	end

	private

	def review_params
		params.require(:review).permit(:title, :body)
	end
end

app/controllers/polishes_controller.rb
class PolishesController < ApplicationController
  def index
  	@polishes = Polish.all
    authorize @polishes
  end

  def show
  	@polish = Polish.find(params[:id])
    @reviews = @polish.reviews
    @review = Review.new
    @favorited = @polish.favorite_users
    @wanted = @polish.wanted_users
    @owned = @polish.owned_users
  end

  def new
    @polish = Polish.new
    authorize @polish
  end

  def create
    @polish = current_user.polishes.build(polish_params)
    authorize @polish
    if @polish.save
      flash[:notice] = "Polish saved!"
      redirect_to @polish
    else
      flash[:error] = "There was a problem saving your polish. Please try again."
      render :new
    end
  end

  def destroy
    @polish = Polish.find(params[:id])
    name = @polish.name

    authorize @polish
    if @polish.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to polishes_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end

  def edit
    @polish = Polish.find(params[:id])
    authorize @polish
  end

  def update
    @polish = Polish.find(params[:id])
    authorize @polish
    if @polish.update_attributes(polish_params)
      flash[:notice] = "Polish details updated."
      redirect_to @polish
    else
      flash[:error] = "There was an error saving this polish. Please try again!"
      render :edit
    end
  end

  private
  def polish_params
    params.require(:polish).permit(:brand, :name, :color, :style)
  end
end

app/helpers/polishes_helper.rb
module PolishesHelper
end

app/views/polishes/_form.html.erb
<%= form_for @polish do |f| %>
  <% if polish.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(polish.errors.count, "error") %>.</h4>
      <ul>
        <% polish.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(polish.errors[:brand]) do %>
	<%= f.label :brand %>
	<%= f.text_field :brand %>
  <% end %>
  <%= form_group_tag(polish.errors[:name]) do %>
	<%= f.label :name %>
	<%= f.text_field :name %>
  <% end %>
  <%= form_group_tag(polish.errors[:color]) do %>
	<%= f.label :color %>
	<%= f.text_field :color %>
  <% end %>
  <%= form_group_tag(polish.errors[:style]) do %>
	<%= f.label :style %>
	<%= f.select :style, [
		['Normal', 'Normal'], 
		['Matte', 'Matte'], 
		['Glitter', 'Glitter'], 
		['Metallic', 'Metallic'], 
		['Gel', 'Gel']] %>
  <% end %>
  <div class="form-group">
	<%= f.submit "Save Polish!" %>
  </div>
<% end %>

app/views/polishes/edit.html.erb
<div class="container">
	<h1>Edit Polish</h1>
	<div class="row">
		<div class="col-md-4">
			Make changes to an existing polish.
		</div>
		<div class="col-md-8">
		<%= render partial: 'form', locals: { polish: @polish } %>
		</div>
	</div>
</div>

app/views/polishes/index.html.erb
<div class="container">
	<h1>All Polishes
		<small>
		<% if policy(Polish.new).create? %>
			<%= link_to ("<i class='fa fa-plus'></i> New Polish").html_safe, new_polish_path, class: 'btn btn-default' %>
		<% end %>
		</small>
	</h1>

		<div class="table-responsive">
			<table class="table">
				<thead>
					<tr>
						<th>Nail Polish</th>
						<th>Color</th>
						<th>Style</th>
					</tr>
				</thead>
				<tbody>
					<% @polishes.each do |polish| %>
						<tr>
							<td>
							<%= link_to "#{polish.brand}'s #{polish.name}", polish %>
							</td>
							<td>
								<%= polish.color.capitalize %>
							</td>
							<td>
								<%= polish.style %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
</div>

app/views/polishes/new.html.erb
<div class="container">
	<h1>Add Polish</h1>
	<div class="row">
		<div class="col-md-4">
			Add a new nail polish.
		</div>
		<div class="col-md-8">
			<%= render partial: 'form', locals: { polish: @polish } %>
		</div>
	</div>
</div>

app/views/polishes/show.html.erb
<div class="container">
	<h1><%= @polish.brand %>'s <%= @polish.name %> 
	<small>
		<% if current_user %>
		<%= render partial: 'favorites/favorite', locals: { polish: @polish } %>
		<%= render partial: 'owns/own', locals: { polish: @polish } %>
		<%= render partial: 'wants/want', locals: { polish: @polish } %>
	<% end %>
	</small>
	</h1>
	
	<p>Color: <%= @polish.color.capitalize %></p>
	<p>Style: <%= @polish.style %> </p>

	<% if policy(@polish).edit? %>
		<%= link_to ("<i class='fa fa-pencil'></i> Edit Polish").html_safe, edit_polish_path(@polish), class: 'btn btn-default' %>
	<% end %>
	<% if policy(@polish).destroy? %>
		<%= link_to ("<i class='fa fa-trash-o'></i> Delete Polish").html_safe, @polish, method: :delete, class: 'btn btn-default', data: {  confirm: 'Are you sure you want to delete this polish? '} %>
	<%end%>

	<h3>Polish Reviews</h3>
	<% @reviews.each do |review| %>
	<p><%= link_to review.title, polish_review_path(@polish, review) %> by <%= link_to review.user.name, user_path(review.user) %></p>
	<% end %>
	<% if policy(@review).create? %>
			<%= link_to ("<i class='fa fa-plus'></i> Add a Review").html_safe, new_polish_review_path(@polish), class: 'btn btn-default' %>
	<% end %>

	<h3>Favorited by</h3>
	<% if @favorited.each do |user| %>
		<p><%= link_to user.name, user_path(user) %></p>
	<% end.empty? %>
		No one's here yet!
	<% end %>

	<h3>Owned by</h3>
	<% if @owned.each do |user| %>
		<p><%= link_to user.name, user_path(user) %></p>
	<% end.empty? %>
		No one's here yet!
	<% end %>

	<h3>Wanted by</h3>
	<% if @wanted.each do |user| %>
		<p><%= link_to user.name, user_path(user) %></p>
	<% end.empty? %>
		No one's here yet!
	<% end %>
</div>